# Generated by Django 5.0.4 on 2024-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_named_url_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_location_url',
            field=models.CharField(blank=True, default='https://127.0.0.1:8000/', max_length=255),
        ),
    ]
