# Generated by Django 5.0.4 on 2024-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_menu_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_location_url',
            field=models.CharField(blank=True, default='/', max_length=255),
        ),
    ]
